export const ADMIN_PERMISSIONS = [
  'news.view',
  'news.manage',
  'news.create',
  'news.update',
  'news.delete',
  'policy.view',
  'policy.manage',
  'policy.update',
  'blacklist.view',
  'blacklist.manage',
  'customer.view',
  'customer.manage',
  'review.view',
  'review.reply',
  'review.moderate',
  'staff.view',
  'staff.manage',
  'employee.view',
  'employee.manage',
  'role.manage',
  'log.view',
  'system.log',
];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  QuanTriVien: ADMIN_PERMISSIONS,
  BanQuanLy: ['finance.view', 'report.view', 'report.export'],
  NhanVienDieuPhoi: [
    'route.view',
    'route.manage',
    'vehicle.view',
    'vehicle.manage',
    'driver.view',
    'driver.manage',
    'stop.view',
    'stop.manage',
    'trip.view',
    'trip.create',
    'trip.assign',
    'trip.update',
  ],
  NhanVienBanVe: [
    'ticket.view',
    'ticket.sell',
    'ticket.cancel',
    'ticket.update',
    'ticket.manage',
    'customer.view',
  ],
};
